### **Setup: Imports und Initialisierung**

In [ ]:
import sys
import os
import glob
sys.path.append(os.path.abspath('..'))

from quinex_application.scopus_data import ProcessScopusData
from quinex_application.visualisation_metadata import VisualisationMetadata

In [ ]:
output_path = "../data/paper/paper_dataset.parquet"
csvs_paths = glob.glob("../data/external/scopus_query4/by_years/scopus_*.csv")
query_name = 'Query: TITLE-ABS-KEY ( ( "energy system*" ) AND ( simul* OR model* OR "plan" OR "plans" OR "planning" OR optimi* OR analy* OR assess* OR evaluat* ) ) AND ( LIMIT-TO ( OA , "all" ) ) AND ( LIMIT-TO ( SUBJAREA , "ENGI" ) OR LIMIT-TO ( SUBJAREA , "ENER" ) OR LIMIT-TO ( SUBJAREA , "ENVI" ) ) AND ( LIMIT-TO ( LANGUAGE , "English" ) )'
query_date = "14.05.2025"
quelle_name = "Source: Scopus"

scopus = ProcessScopusData(csvs_paths, output_path, query_name, query_date, quelle_name) 
visualisation = VisualisationMetadata(output_path)

## **Load and Clean CSV Files**

### **Combine the CSV Files**

In [32]:
df = scopus.combine_csvs()
print(len(df))

25413

### **Clean duplicate DOIs**

In [33]:
duplicate_doi_values = df["DOI"].value_counts()
duplicate_doi_values = duplicate_doi_values[duplicate_doi_values > 1]
print(f"Anzahl verschiedener mehrfacher DOIs: {len(duplicate_doi_values)}")
print(f"Anzahl an Zeilen mit mehrfacher DOI: {duplicate_doi_values.sum()}")

Anzahl verschiedener mehrfacher DOIs: 29
Anzahl an Zeilen mit mehrfacher DOI: 58

In [34]:
df_cleaned = scopus.remove_duplicates_doi()
print(len(df_cleaned))

25384

### **Add new Papers to Parquet**

In [35]:
# TODO: Quinex und Query sollen per Default auf False gesetzt werden, falls nicht durchgeführt oder dort enthalten
parquet = scopus.update_parquet_with_new_data()
display(parquet)

,Year,Source title,Cited by,DOI,Link,Open Access,Source: Scopus,"Query: TITLE-ABS-KEY ( energy AND system AND analysis ) AND ( LIMIT-TO ( OA , ""all"" ) ) AND ( LIMIT-TO ( LANGUAGE , ""English"" ) )_30.04.2025","Query: TITLE-ABS-KEY ( ( ""energy research"" OR ""energy system*"" OR ""integrated assessment model*"" ) AND ( ""analys*"" OR ""model*"" OR ""optimiz*"" OR ""technolog*"" OR ""power plant*"" ) ) AND ( LIMIT-TO ( OA , ""all"" ) ) AND ( LIMIT-TO ( LANGUAGE , ""English"" ) )_08.05.2025","Query: TITLE-ABS-KEY ( ( ""energy system*"" ) AND ( simul* OR model* OR ""plan"" OR ""plans"" OR ""planning"" OR optimi* OR analy* OR assess* OR evaluat* ) ) AND ( LIMIT-TO ( OA , ""all"" ) ) AND ( LIMIT-TO ( LANGUAGE , ""English"" ) )_14.05.2025",Quinex,Quinex_ID,Quinex_Version,Lizenz,OEO_Version
0,1919,Proceedings of the Physical Society of London,2.0,10.1088/1478-7814/32/1/335,https://www.scopus.com/inward/record.uri?eid=2-s2.0-36149071527&doi=10.1088%2f1478-7814%2f32%2f1%2f335&partnerID=40&md5=39d25363418e86fa9f68e6d479f4dd94,Green Open Access,True,True,True,False,False,<NA>,<NA>,<NA>,<NA>
1,1948,Physical Review,4795.0,10.1103/PhysRev.73.679,https://www.scopus.com/inward/record.uri?eid=2-s2.0-33745930076&doi=10.1103%2fPhysRev.73.679&partnerID=40&md5=446baa7597afb24a8900cbbfe2618fe2,Bronze Open Access; Green Open Access,True,True,True,False,False,<NA>,<NA>,<NA>,<NA>
2,1949,Physical Review,35.0,10.1103/PhysRev.75.1637,https://www.scopus.com/inward/record.uri?eid=2-s2.0-0007024833&doi=10.1103%2fPhysRev.75.1637&partnerID=40&md5=9aacc4d57574e803365a7635985edfd5,Green Open Access,True,True,True,False,False,<NA>,<NA>,<NA>,<NA>
3,1952,The Journal of general physiology,8.0,10.1085/jgp.36.2.181,https://www.scopus.com/inward/record.uri?eid=2-s2.0-0007440133&doi=10.1085%2fjgp.36.2.181&partnerID=40&md5=f5193dd8ee40573bfdad90ea970c85e9,Bronze Open Access; Green Open Access,True,True,True,False,False,<NA>,<NA>,<NA>,<NA>
4,1955,Journal of Inorganic and Nuclear Chemistry,3.0,10.1016/0022-1902(55)80065-6,https://www.scopus.com/inward/record.uri?eid=2-s2.0-50449121789&doi=10.1016%2f0022-1902%2855%2980065-6&partnerID=40&md5=2da0b49bc3ab506e92e5d009ee0cc158,Green Open Access,True,True,True,True,False,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183289,2025,Results in Physics,0.0,10.1016/j.rinp.2025.108277,https://www.scopus.com/inward/record.uri?eid=2-s2.0-105003865273&doi=10.1016%2fj.rinp.2025.108277&partnerID=40&md5=7204268dcbe85b024fd1ded875a25751,Gold Open Access,True,False,False,True,False,<NA>,<NA>,<NA>,<NA>
183290,2025,Sustainable Futures,0.0,10.1016/j.sftr.2025.100637,https://www.scopus.com/inward/record.uri?eid=2-s2.0-105003925317&doi=10.1016%2fj.sftr.2025.100637&partnerID=40&md5=b56c2412c504f5677ad272f43fbb59b2,Gold Open Access,True,False,False,True,False,<NA>,<NA>,<NA>,<NA>
183291,2025,Advances in Geo-Energy Research,0.0,10.46690/ager.2025.03.02,https://www.scopus.com/inward/record.uri?eid=2-s2.0-86000767572&doi=10.46690%2fager.2025.03.02&partnerID=40&md5=55d02b8156e43bb0be622a85be11395d,Gold Open Access,True,False,False,True,False,<NA>,<NA>,<NA>,<NA>
183292,2025,International Transactions on Electrical Energy Systems,0.0,10.1155/etep/2734170,https://www.scopus.com/inward/record.uri?eid=2-s2.0-105000499948&doi=10.1155%2fetep%2f2734170&partnerID=40&md5=4e14d9b196e13cc45d67c9d17282a32e,Gold Open Access,True,False,False,True,False,<NA>,<NA>,<NA>,<NA>
183293,2025,Chemical Science,0.0,10.1039/d5sc01390a,https://www.scopus.com/inward/record.uri?eid=2-s2.0-105003088233&doi=10.1039%2fd5sc01390a&partnerID=40&md5=24eae0578d2a3a008c3dea041f7b7701,Gold Open Access,True,False,False,True,False,<NA>,<NA>,<NA>,<NA>

### **Save cleaned and added data**

In [ ]:
df = scopus.save_df()

None

## **Analyse Metadata**

In [38]:
import pandas as pd
df = pd.read_parquet(output_path)
display(df)

,Year,Source title,Cited by,DOI,Link,Open Access,Source: Scopus,"Query: TITLE-ABS-KEY ( energy AND system AND analysis ) AND ( LIMIT-TO ( OA , ""all"" ) ) AND ( LIMIT-TO ( LANGUAGE , ""English"" ) )_30.04.2025","Query: TITLE-ABS-KEY ( ( ""energy research"" OR ""energy system*"" OR ""integrated assessment model*"" ) AND ( ""analys*"" OR ""model*"" OR ""optimiz*"" OR ""technolog*"" OR ""power plant*"" ) ) AND ( LIMIT-TO ( OA , ""all"" ) ) AND ( LIMIT-TO ( LANGUAGE , ""English"" ) )_08.05.2025","Query: TITLE-ABS-KEY ( ( ""energy system*"" ) AND ( simul* OR model* OR ""plan"" OR ""plans"" OR ""planning"" OR optimi* OR analy* OR assess* OR evaluat* ) ) AND ( LIMIT-TO ( OA , ""all"" ) ) AND ( LIMIT-TO ( LANGUAGE , ""English"" ) )_14.05.2025",Quinex,Quinex_ID,Quinex_Version,Lizenz,OEO_Version
0,1919,Proceedings of the Physical Society of London,2.0,10.1088/1478-7814/32/1/335,https://www.scopus.com/inward/record.uri?eid=2-s2.0-36149071527&doi=10.1088%2f1478-7814%2f32%2f1%2f335&partnerID=40&md5=39d25363418e86fa9f68e6d479f4dd94,Green Open Access,True,True,True,False,False,None,None,None,None
1,1948,Physical Review,4795.0,10.1103/PhysRev.73.679,https://www.scopus.com/inward/record.uri?eid=2-s2.0-33745930076&doi=10.1103%2fPhysRev.73.679&partnerID=40&md5=446baa7597afb24a8900cbbfe2618fe2,Bronze Open Access; Green Open Access,True,True,True,False,False,None,None,None,None
2,1949,Physical Review,35.0,10.1103/PhysRev.75.1637,https://www.scopus.com/inward/record.uri?eid=2-s2.0-0007024833&doi=10.1103%2fPhysRev.75.1637&partnerID=40&md5=9aacc4d57574e803365a7635985edfd5,Green Open Access,True,True,True,False,False,None,None,None,None
3,1952,The Journal of general physiology,8.0,10.1085/jgp.36.2.181,https://www.scopus.com/inward/record.uri?eid=2-s2.0-0007440133&doi=10.1085%2fjgp.36.2.181&partnerID=40&md5=f5193dd8ee40573bfdad90ea970c85e9,Bronze Open Access; Green Open Access,True,True,True,False,False,None,None,None,None
4,1955,Journal of Inorganic and Nuclear Chemistry,3.0,10.1016/0022-1902(55)80065-6,https://www.scopus.com/inward/record.uri?eid=2-s2.0-50449121789&doi=10.1016%2f0022-1902%2855%2980065-6&partnerID=40&md5=2da0b49bc3ab506e92e5d009ee0cc158,Green Open Access,True,True,True,True,False,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183289,2025,Results in Physics,0.0,10.1016/j.rinp.2025.108277,https://www.scopus.com/inward/record.uri?eid=2-s2.0-105003865273&doi=10.1016%2fj.rinp.2025.108277&partnerID=40&md5=7204268dcbe85b024fd1ded875a25751,Gold Open Access,True,False,False,True,False,None,None,None,None
183290,2025,Sustainable Futures,0.0,10.1016/j.sftr.2025.100637,https://www.scopus.com/inward/record.uri?eid=2-s2.0-105003925317&doi=10.1016%2fj.sftr.2025.100637&partnerID=40&md5=b56c2412c504f5677ad272f43fbb59b2,Gold Open Access,True,False,False,True,False,None,None,None,None
183291,2025,Advances in Geo-Energy Research,0.0,10.46690/ager.2025.03.02,https://www.scopus.com/inward/record.uri?eid=2-s2.0-86000767572&doi=10.46690%2fager.2025.03.02&partnerID=40&md5=55d02b8156e43bb0be622a85be11395d,Gold Open Access,True,False,False,True,False,None,None,None,None
183292,2025,International Transactions on Electrical Energy Systems,0.0,10.1155/etep/2734170,https://www.scopus.com/inward/record.uri?eid=2-s2.0-105000499948&doi=10.1155%2fetep%2f2734170&partnerID=40&md5=4e14d9b196e13cc45d67c9d17282a32e,Gold Open Access,True,False,False,True,False,None,None,None,None
183293,2025,Chemical Science,0.0,10.1039/d5sc01390a,https://www.scopus.com/inward/record.uri?eid=2-s2.0-105003088233&doi=10.1039%2fd5sc01390a&partnerID=40&md5=24eae0578d2a3a008c3dea041f7b7701,Gold Open Access,True,False,False,True,False,None,None,None,None

In [ ]:
visualisation.load_df()
display(visualisation.df.head())
print(len(visualisation.df))

### **Paper pro Jahr**

In [ ]:
fig = visualisation.paper_per_year(start_year = 1995)
fig.show()

### **Zitierungen pro Jahr**

In [ ]:
fig = visualisation.citations_per_year(start_year = 1995)
fig.show()

### **Journal**

In [ ]:
fig = visualisation.top_journals(number=15, by="count")
fig.show()

In [ ]:
fig = visualisation.journal_trend("Energies")
fig.show()

### **Open Access**

In [ ]:
fig = visualisation.open_access()
fig.show()

In [ ]:
fig = visualisation.citations_open_access()
fig.show()

### **Top Paper**

In [ ]:
fig = visualisation.top_cited_papers(20, (12, 5))
fig.show()